# Kernel SVM

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('synthetic_IoMT_70.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [4]:
print(X_train)

[[ 96.          13.           1.44367738   2.81761368  96.93657542]
 [ 93.          14.           2.55065111   0.60061309  96.13646317]
 [119.          13.           4.28908256   4.76047811  96.68220808]
 ...
 [101.          16.           4.1682026    4.48437309  96.49372147]
 [115.          17.           1.98926568   4.47200591  96.67870097]
 [153.          14.           1.21517756   1.30087206  97.06215776]]


In [5]:
print(y_train)

[0 0 0 ... 0 0 1]


In [6]:
print(X_test)

[[ 84.          17.           4.58368243   4.01733882  96.56794205]
 [102.          17.           4.22115672   8.87346352  90.60904768]
 [109.          14.           1.29858853   0.91604157  95.96742769]
 ...
 [ 93.          14.           2.48506688   3.72902906  89.54665941]
 [ 80.          12.           3.35631995   4.04748365  95.18685031]
 [143.          34.           7.50048429   2.19464129  91.34315393]]


In [7]:
print(y_test)

[0 1 0 ... 1 0 1]


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[-0.33775729 -0.71483705 -0.69491394 -0.00360684  0.66281478]
 [-0.42967524 -0.52793221 -0.17066706 -0.84117671  0.39227634]
 [ 0.36694699 -0.71483705  0.65262914  0.73039599  0.57680667]
 ...
 [-0.18456071 -0.15412251  0.59538212  0.62608513  0.51307452]
 [ 0.24438972  0.03278233 -0.43653114  0.62141288  0.57562083]
 [ 1.40868374 -0.52793221 -0.80312817 -0.57662297  0.70527739]]


In [10]:
print(X_test)

[[-0.70542909  0.03278233  0.79214741  0.44964231  0.5381704 ]
 [-0.15392139  0.03278233  0.62046043  2.28425786 -1.47668437]
 [ 0.06055382 -0.52793221 -0.76362593 -0.72200968  0.33512112]
 ...
 [-0.42967524 -0.52793221 -0.20172681  0.34072057 -1.83590504]
 [-0.82798635 -0.9017419   0.21088615  0.46103085  0.07118792]
 [ 1.10229058  3.2101647   2.17350292 -0.23896217 -1.22846425]]


## Training the Kernel SVM model on the Training set

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Predicting a new result

In [12]:
#print(classifier.predict(sc.transform([[30,87000]])))

## Predicting the Test set results

In [13]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [1 1]
 [0 0]
 [1 1]]


## Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11873    56]
 [  399 11672]]


0.9810416666666667

In [15]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from numpy import mean
from numpy import std

# prepare the cross-validation procedure
cv = KFold(n_splits=10, random_state=0, shuffle=True)

# evaluate model
scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.952 (0.002)
